### ISSUE TITLE
modernizr

### ISSUE THREAD

**Issue by oldchestnut** [scottnix/childs-play#5]
How much of modernizr can be removed considering that there is a html5 shiv in thematic 2 beta now, and with XP / IE8 no longer supported  by Microsoft?

**Comment by scottnix** [comment]
Pretty much everything in modernizr can be removed, except for the "Add CSS Classes".

The menu functionality kind of depends on the `.js` or `no-js` check. So if no javascript is available, the mobile version of the menu will instead be shown by default (since the toggle depends on JavaScript to work).

So yeah, I probably should get rid of the full production version and switch to only CSS Classes and the Shiv.

The Shiv in Thematic 2.0 is setup to detect if modernizr is used (if you enqueue the script correctly), so it doesn't double load it. The way I am using it on my current theme (scottnix.com) is to only load the CSS Classes, also removed shiv, but thematic doesn't load it either... THEN! I even load modernizr in the footer, which is abnormal, but whether you can do it or not depends totally how you are using it.

Keep in mind that just because IE8/xp are no longer supported you really have to look at the site Analytics to know how many people are using it and base your judgement on that instead. :)

**Comment by scottnix** [comment]
I updated both versions to a modernizr version that includes just the shiv and necessary CSS classes, too many people weren't updating it to a production version, so might as well.

**Comment by oldchestnut** [comment]
That's great - thanks for the clarification and creating the optimized modernizr version.
